### ISSUE TITLE
CI: `release-please-action` downgrades version

### ISSUE THREAD

**Issue by rndquu** [ubiquibot/permit-generation#28]
Check [this](https://github.com/ubiquibot/permit-generation/pull/23) PR which was created automatically by [this](https://github.com/ubiquibot/permit-generation/blob/37e28cca5f9a31f62a03e622eeeb7dcfad132aa4/.github/workflows/publish-package.yml) workflow.

[Initially](https://github.com/ubiquibot/permit-generation/pull/23/commits/a43f502d23c00362897b98b21dd2c950cd399941) that PR downgraded the package version to `1.0.0` although the expected behavior was to bump the version.

What should be done:
- find out and fix the root cause why [google-github-actions/release-please-action](https://github.com/ubiquibot/permit-generation/blob/37e28cca5f9a31f62a03e622eeeb7dcfad132aa4/.github/workflows/publish-package.yml#L17) downgrades the version instead of bumping it 
- make sure that on every new commit with message pattern `feat: *` a new PR is created with a bumped version

P.S. Expected release [flow](https://github.com/ubiquibot/permit-generation/pull/23#issuecomment-2178005450)

**Comment by rndquu** [comment]
@gentlementlegen Pls check the description

**Comment by gentlementlegen** [comment]
My guess is that because the package was previously released manually, it doesn't match the version on the repo. Afaik `release-please` will look for the all the commit names, then check the current package version and the repo latest tag. And it seems there is currently no tag inside this repository which would bring it back to `1.0.0` (just a guess).
Also the package should be changed to https://github.com/googleapis/release-please since the previous one is now deprecated.

**Comment by gentlementlegen** [comment]
@rndquu It seems the publishing failed somehow: https://github.com/ubiquibot/permit-generation/actions/runs/9854824504/job/27208423101#step:6:15 investigating

**Comment by gentlementlegen** [comment]
@rndquu Re-ran publishing and everything went fine https://github.com/ubiquibot/permit-generation/actions/runs/9858376185
Latest npm: https://www.npmjs.com/package/@ubiquibot/permit-generation

**Comment by rndquu** [comment]
> @rndquu Re-ran publishing and everything went fine https://github.com/ubiquibot/permit-generation/actions/runs/9858376185 Latest npm: https://www.npmjs.com/package/@ubiquibot/permit-generation

So this issue should be closed as completed, right?

**Comment by gentlementlegen** [comment]
@rndquu I believe the version should never be downgraded moving forward. Let's keep an eye on it and eventually re-open the ticket but we should be good to go!
