### ISSUE TITLE
Duplicated nonces

### ISSUE THREAD

**Issue by rndquu** [ubiquibot/permit-generation#46]
Nonces for some github issues are duplicated hence reward claiming is broken for those issues.

Check the following reward URLs:
- https://github.com/ubiquibot/user-activity-watcher/issues/14#issuecomment-2317208648
- https://github.com/ubiquibot/command-start-stop/issues/14#issuecomment-2308374805

In the decoded base64 input all nonces (per user) are equal while the expected behavior is that they should be different.

It happens because [here](https://github.com/ubiquibot/permit-generation/blob/b08723fb0ca280162053013b66873da82320f286/src/handlers/generate-erc20-permit.ts#L111) the nonce is derived from user's github id and github issue number while earlier (not sure when the code was updated) it'd been derived from `issue.node_id`.

What should be done:
- make sure nonces are not duplicated both for ERC20 permits and NFT rewards

**Comment by 0x4007** [comment]
The property name suggests issue ID not issue number. That would work.

**Comment by gentlementlegen** [comment]
Impacted rewards that I've seen so far:
- [ ] https://github.com/ubiquity/ubiquibot-kernel/issues/95#issuecomment-2319639659
- [ ] https://github.com/ubiquibot/user-activity-watcher/issues/14#issuecomment-2317208648
- [ ] https://github.com/ubiquibot/command-start-stop/issues/6#issuecomment-2299954707

**Comment by 0x4007** [comment]
- I was able to claim https://github.com/ubiquity/ubiquibot-kernel/issues/95#issuecomment-2319639659 just now
-

**Comment by gentlementlegen** [comment]
@0x4007 Still not possible to claim for me.

**Comment by Keyrxng** [comment]
> Impacted rewards that I've seen so far:

I added another issue to this list

**Comment by gentlementlegen** [comment]
I will be regenerating the permits listed above and see if they are claimable now.
