### ISSUE TITLE
Package and GitHub agnostic option

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquibot/permit-generation#5]
The package is usable as a GitHub action but does not offer any option to be directly imported in the code of another project.
Having it as a NPM Package would greatly facitate integration within other projects without the hassle of importing submodules, or using Actions.

The package should also offer an option to be GitHub Action agnostic, because its purpose is simply to generate permits.

Tasks to be carried on:
- package, bundle and type the functions within `.d.ts` files
- export the package to NPM
- make overloads of GitHub agnostic permit generation

**Comment by gentlementlegen** [comment]
@pavlovcik This is aimed to help for https://github.com/ubiquibot/conversation-rewards/issues/5 or if eventually we want it to be ran by the kernel itself, related to our [discussion](https://github.com/ubiquibot/conversation-rewards/issues/5#issuecomment-2035427134)

**Comment by pavlovcik** [comment]
I replied and definitely think this is not a task worth pursing.

**Comment by pavlovcik** [comment]
If you want to implement this as a temporary solution, i.e. tech debt, then perhaps it makes sense so that we can get back on track with our schedule.

**Comment by 0x4007** [comment]
> ```diff
> + Evaluating results. Please wait...
> ```

We got rate limited https://github.com/ubiquibot/comment-incentives/actions/runs/8617933701/job/23619113189

**Comment by gitcoindev** [comment]
I triggered once more in debug mode, will not spam anymore here -)
